-- SneakRush - Products.sql (100 produits)
INSERT INTO products (name, brand, description, price, is_limited) VALUES
('Air Zoom XR', 'Nike', 'Sneakers running édition limitée', 249.90, TRUE),
('Air Zoom XR Volt', 'Nike', 'Colorway Volt dynamique', 259.90, TRUE),
('Air Zoom XR Blackout', 'Nike', 'Version noire furtive', 239.90, FALSE),
('Air Max Pulse', 'Nike', 'Amorti Air iconique', 179.90, FALSE),
('Air Max Pulse LTD', 'Nike', 'Série limitée matériaux premium', 209.90, TRUE),
('Dunk Low Panda', 'Nike', 'Noir & blanc classique', 139.90, FALSE),
('Dunk Low University Blue', 'Nike', 'Bleu université frais', 149.90, TRUE),
('Dunk High Forest', 'Nike', 'Vert forêt saisonnier', 159.90, FALSE),
('Blazer Mid 77 Vintage', 'Nike', 'Look rétro cuir', 129.90, FALSE),
('Jordan 1 Retro High Crimson', 'Jordan', 'Palette crimson audacieuse', 199.90, TRUE),
('Jordan 1 Mid Bred Toe', 'Jordan', 'Blocage de couleurs classique', 169.90, FALSE),
('Jordan 4 Craft Taupe', 'Jordan', 'Matériaux texturés premium', 229.90, TRUE),
('Jordan 3 Cement', 'Jordan', 'Motif cement iconique', 219.90, FALSE),
('Jordan 11 Cool Grey', 'Jordan', 'Breveté & mesh', 239.90, TRUE),
('Yeezy 350 V2 Slate', 'adidas', 'Primeknit respirant', 219.90, TRUE),
('Yeezy 700 Wave', 'adidas', 'Silhouette chunky', 259.90, TRUE),
('Ultraboost 23 Core', 'adidas', 'Confort quotidien Boost', 179.90, FALSE),
('Ultraboost 23 LTD', 'adidas', 'Colorway limité', 189.90, TRUE),
('Forum Low White', 'adidas', 'Style rétro 80s', 109.90, FALSE),
('Forum Mid Beige', 'adidas', 'Tige mid polyvalente', 119.90, FALSE),
('Campus 00s Green', 'adidas', 'Suède vert profond', 99.90, FALSE),
('Campus 00s Pink', 'adidas', 'Suède rose pastel', 99.90, FALSE),
('Samba OG Black', 'adidas', 'Classique intemporel', 99.90, FALSE),
('Samba OG LTD Gum', 'adidas', 'Semelle gomme édition', 109.90, TRUE),
('Gazelle Bold Blue', 'adidas', 'Plateforme subtile', 119.90, FALSE),
('New Balance 550 White Green', 'New Balance', 'Basket rétro basket-ball', 139.90, FALSE),
('New Balance 550 UNC', 'New Balance', 'Bleu universitaire populaire', 149.90, TRUE),
('New Balance 2002R Protection Pack', 'New Balance', 'Esthétique déstructurée', 199.90, TRUE),
('New Balance 9060 Quartz', 'New Balance', 'Look futuriste', 169.90, FALSE),
('New Balance 1906R Metallic', 'New Balance', 'Runner métallique', 179.90, TRUE),
('Puma Suede Classic Black', 'Puma', 'Icône suède', 89.90, FALSE),
('Puma Slipstream White', 'Puma', 'B-ball rétro', 109.90, FALSE),
('Puma RS-X Multicolor', 'Puma', 'Couleurs vives', 129.90, FALSE),
('Asics Gel-Kayano 14 Silver', 'ASICS', 'Stabilité & rétro', 159.90, TRUE),
('Asics Gel-Nimbus 26 Black', 'ASICS', 'Confort longue distance', 169.90, FALSE),
('Salomon XT-6 Vanilla', 'Salomon', 'Trail urbain culte', 179.90, TRUE),
('Salomon ACS Pro Black', 'Salomon', 'Tech utilitaire', 189.90, TRUE),
('Reebok Club C 85 Chalk', 'Reebok', 'Cuir vintage', 89.90, FALSE),
('Reebok Classic Leather Gum', 'Reebok', 'Semelle gomme rétro', 99.90, FALSE),
('Converse Chuck 70 Hi Black', 'Converse', 'Toile premium', 89.90, FALSE),
('Converse Chuck 70 Hi LTD Patchwork', 'Converse', 'Patchwork limité', 119.90, TRUE),
('Vans Old Skool Black', 'Vans', 'Bande latérale iconique', 79.90, FALSE),
('Vans Sk8-Hi Checkerboard', 'Vans', 'Damier classique', 89.90, FALSE),
('Nike Tech Fleece Full Zip', 'Nike', 'Hoodie Tech Fleece', 129.90, FALSE),
('Nike Tech Fleece Joggers', 'Nike', 'Pantalon fuselé', 119.90, FALSE),
('Nike ACG Cargo Pants', 'Nike ACG', 'Pantalon cargo technique', 139.90, TRUE),
('Jordan Essentials Hoodie', 'Jordan', 'Molleton brossé', 99.90, FALSE),
('Jordan Utility Cargo', 'Jordan', 'Pantalon utility', 129.90, TRUE),
('adidas Firebird Track Jacket', 'adidas', 'Veste survêt classique', 89.90, FALSE),
('adidas Firebird Track Pants', 'adidas', 'Pantalon survêt', 79.90, FALSE),
('adidas Adicolor Hoodie', 'adidas', 'Coupe régulière', 69.90, FALSE),
('New Balance Athletics Tee', 'New Balance', 'T-shirt coton lourd', 39.90, FALSE),
('New Balance Cargo Shorts', 'New Balance', 'Short cargo', 59.90, FALSE),
('Puma Classics Hoodie', 'Puma', 'Logo brodé', 69.90, FALSE),
('Puma Cargo Track Pants', 'Puma', 'Pantalon technique', 79.90, FALSE),
('ASICS x Andersson Bell Tee', 'ASICS', 'Collab tee limité', 49.90, TRUE),
('Salomon Advanced Vest', 'Salomon', 'Gilet technique', 119.90, TRUE),
('Reebok Vector Hoodie', 'Reebok', 'Capuche logo', 59.90, FALSE),
('Converse Star Tee', 'Converse', 'Tee graphique', 34.90, FALSE),
('Vans Classic Hoodie', 'Vans', 'Molleton classique', 64.90, FALSE),
('Vans Authentic Chino', 'Vans', 'Chino coupe droite', 69.90, FALSE),
('Carhartt WIP Hoodie Chase', 'Carhartt WIP', 'Coton épais', 89.90, FALSE),
('Carhartt WIP Single Knee Pant', 'Carhartt WIP', 'Durable workwear', 99.90, FALSE),
('Stüssy Logo Tee', 'Stüssy', 'Tee logo street', 49.90, TRUE),
('Stüssy Beach Shorts', 'Stüssy', 'Short léger', 79.90, TRUE),
('The North Face Nuptse Vest', 'The North Face', 'Doudoune sans manches', 189.90, TRUE),
('The North Face Tek Hoodie', 'The North Face', 'Hoodie technique', 119.90, FALSE),
('Patagonia Better Sweater', 'Patagonia', 'Laine polaire', 149.90, FALSE),
('Patagonia Baggies Shorts', 'Patagonia', 'Short nylon', 69.90, FALSE),
('Stone Island Badge Tee', 'Stone Island', 'Badge manche', 119.90, TRUE),
('Stone Island Cargo Pant', 'Stone Island', 'Cargo premium', 289.90, TRUE),
('Nike Air Force 1 White', 'Nike', 'AF1 cuir blanc', 109.90, FALSE),
('Nike Air Force 1 Shadow', 'Nike', 'Superpositions féminines', 119.90, FALSE),
('Nike Air Force 1 LTD Jewel', 'Nike', 'Swoosh Jewel limité', 129.90, TRUE),
('Jordan 1 Low Mocha', 'Jordan', 'Teinte Mocha', 159.90, TRUE),
('Jordan 1 Low Triple White', 'Jordan', 'Tout blanc polyvalent', 139.90, FALSE),
('adidas Rivalry Low Orange', 'adidas', 'Basket rétro 80s', 109.90, FALSE),
('adidas Spezial Navy', 'adidas', 'Silhouette terrace', 99.90, FALSE),
('New Balance 574 Core Grey', 'New Balance', 'Classique 574', 99.90, FALSE),
('New Balance 327 Sea Salt', 'New Balance', 'Look 70s moderne', 119.90, FALSE),
('Puma Palermo Blue', 'Puma', 'Terrace revival', 99.90, TRUE),
('ASICS Gel-Lyte III OG', 'ASICS', 'Languette fendue', 129.90, FALSE),
('Salomon XT-4 OG Black', 'Salomon', 'Version OG technique', 199.90, TRUE),
('Reebok Beatnik Camo', 'Reebok', 'Sandale outdoor', 89.90, TRUE),
('Converse Run Star Hike', 'Converse', 'Semelle crantée', 119.90, FALSE),
('Vans Knu Skool Black', 'Vans', 'Gros padding', 99.90, FALSE),
('Nike Solo Swoosh Tee', 'Nike', 'Tee minimaliste', 39.90, FALSE),
('Nike Club Fleece Joggers', 'Nike', 'Joggers classiques', 64.90, FALSE),
('Jordan Flight Tee', 'Jordan', 'Tee graphique Jumpman', 39.90, FALSE),
('adidas Essentials Hoodie', 'adidas', 'Hoodie cosy', 59.90, FALSE),
('adidas Skate Pants', 'adidas', 'Pantalon skate', 74.90, FALSE),
('New Balance Essentials Hoodie', 'New Balance', 'Logo NB', 69.90, FALSE),
('Puma Essential Tee', 'Puma', 'Tee basique', 24.90, FALSE),
('ASICS Court Tee', 'ASICS', 'Tennis-inspired', 29.90, FALSE),
('Salomon Trail Tee', 'Salomon', 'Tee respirant', 34.90, FALSE),
('Reebok Nano Tee', 'Reebok', 'Training tee', 29.90, FALSE),
('Converse Embroidered Tee', 'Converse', 'Logo brodé', 34.90, FALSE),
('Vans Skate Half Zip', 'Vans', 'Half zip skate', 79.90, FALSE),
('Carhartt WIP Detroit Jacket', 'Carhartt WIP', 'Veste iconique', 199.90, TRUE),
('Carhartt WIP Pocket Tee', 'Carhartt WIP', 'Poche poitrine', 34.90, FALSE),
('Stüssy 8 Ball Hoodie', 'Stüssy', 'Graphique 8 Ball', 129.90, TRUE),
('The North Face Mountain Jacket', 'The North Face', 'Shell imperméable', 279.90, TRUE),
('Patagonia Torrentshell 3L', 'Patagonia', 'Shell 3 couches', 229.90, FALSE),
('Stone Island Overshirt Nylon', 'Stone Island', 'Nylon Metal', 349.90, TRUE),
('Nike ACG Therma-FIT Jacket', 'Nike ACG', 'Isolation légère', 199.90, TRUE),
('adidas Terrex Swift R3', 'adidas Terrex', 'Chaussure outdoor', 149.90, FALSE),
('New Balance Fresh Foam 1080', 'New Balance', 'Cushioning maximal', 179.90, FALSE),
('Puma MB.03 Toxic', 'Puma', 'Basketball signature', 149.90, TRUE),
('ASICS Metaspeed Sky', 'ASICS', 'Racing carbone', 249.90, TRUE),
('Salomon Pulsar Trail', 'Salomon', 'Trail dynamique', 139.90, FALSE),
('Reebok Club C LTD Denim', 'Reebok', 'Edition denim', 109.90, TRUE),
('Converse One Star Pro', 'Converse', 'Skate performance', 89.90, FALSE),
('Vans Half Cab 92', 'Vans', 'Skate légendaire', 99.90, FALSE);
