-- SneakRush - Reviews.sql
-- 50 avis clients de test (sans caractères spéciaux problématiques)

INSERT INTO reviews (product_id, user_id, rating, comment, created_at) VALUES (93, 81, 1, 'Matériaux de bonne qualité.', NOW());
INSERT INTO reviews (product_id, user_id, rating, comment, created_at) VALUES (59, 46, 4, 'Livraison rapide et produit bien emballé.', NOW());
INSERT INTO reviews (product_id, user_id, rating, comment, created_at) VALUES (66, 16, 5, 'Matériaux de bonne qualité.', NOW());
INSERT INTO reviews (product_id, user_id, rating, comment, created_at) VALUES (35, 6, 2, 'Couleur conforme aux photos.', NOW());
INSERT INTO reviews (product_id, user_id, rating, comment, created_at) VALUES (29, 98, 5, 'Parfait pour un usage quotidien.', NOW());
INSERT INTO reviews (product_id, user_id, rating, comment, created_at) VALUES (94, 17, 5, 'Couleur conforme aux photos.', NOW());
INSERT INTO reviews (product_id, user_id, rating, comment, created_at) VALUES (3, 83, 3, 'Bon rapport qualité/prix.', NOW());
INSERT INTO reviews (product_id, user_id, rating, comment, created_at) VALUES (73, 35, 3, 'Bon rapport qualité/prix.', NOW());
INSERT INTO reviews (product_id, user_id, rating, comment, created_at) VALUES (92, 87, 5, 'Matériaux de bonne qualité.', NOW());
INSERT INTO reviews (product_id, user_id, rating, comment, created_at) VALUES (100, 87, 2, 'Un peu serré, prendre une taille au-dessus.', NOW());
INSERT INTO reviews (product_id, user_id, rating, comment, created_at) VALUES (58, 77, 5, 'Très confortable et stylé.', NOW());
INSERT INTO reviews (product_id, user_id, rating, comment, created_at) VALUES (75, 87, 3, 'Un peu serré, prendre une taille au-dessus.', NOW());
INSERT INTO reviews (product_id, user_id, rating, comment, created_at) VALUES (71, 84, 2, 'Super qualité, je recommande !', NOW());
INSERT INTO reviews (product_id, user_id, rating, comment, created_at) VALUES (59, 26, 2, 'Service client réactif.', NOW());
INSERT INTO reviews (product_id, user_id, rating, comment, created_at) VALUES (98, 79, 2, 'Très confortable et stylé.', NOW());
INSERT INTO reviews (product_id, user_id, rating, comment, created_at) VALUES (85, 25, 1, 'Design unique, j''adore.', NOW());
INSERT INTO reviews (product_id, user_id, rating, comment, created_at) VALUES (59, 38, 5, 'Service client réactif.', NOW());
INSERT INTO reviews (product_id, user_id, rating, comment, created_at) VALUES (88, 17, 4, 'Super qualité, je recommande !', NOW());
INSERT INTO reviews (product_id, user_id, rating, comment, created_at) VALUES (51, 11, 1, 'Livraison rapide et produit bien emballé.', NOW());
INSERT INTO reviews (product_id, user_id, rating, comment, created_at) VALUES (98, 47, 3, 'Service client réactif.', NOW());
INSERT INTO reviews (product_id, user_id, rating, comment, created_at) VALUES (41, 55, 4, 'Livraison rapide et produit bien emballé.', NOW());
INSERT INTO reviews (product_id, user_id, rating, comment, created_at) VALUES (24, 98, 3, 'Bon rapport qualité/prix.', NOW());
INSERT INTO reviews (product_id, user_id, rating, comment, created_at) VALUES (68, 54, 1, 'Service client réactif.', NOW());
INSERT INTO reviews (product_id, user_id, rating, comment, created_at) VALUES (61, 51, 3, 'Super qualité, je recommande !', NOW());
INSERT INTO reviews (product_id, user_id, rating, comment, created_at) VALUES (86, 72, 3, 'Matériaux de bonne qualité.', NOW());
INSERT INTO reviews (product_id, user_id, rating, comment, created_at) VALUES (82, 53, 2, 'Matériaux de bonne qualité.', NOW());
INSERT INTO reviews (product_id, user_id, rating, comment, created_at) VALUES (39, 24, 3, 'Un peu serré, prendre une taille au-dessus.', NOW());
INSERT INTO reviews (product_id, user_id, rating, comment, created_at) VALUES (7, 89, 1, 'Livraison rapide et produit bien emballé.', NOW());
INSERT INTO reviews (product_id, user_id, rating, comment, created_at) VALUES (45, 37, 1, 'Super qualité, je recommande !', NOW());
INSERT INTO reviews (product_id, user_id, rating, comment, created_at) VALUES (35, 5, 3, 'Matériaux de bonne qualité.', NOW());
INSERT INTO reviews (product_id, user_id, rating, comment, created_at) VALUES (64, 78, 4, 'Bon rapport qualité/prix.', NOW());
INSERT INTO reviews (product_id, user_id, rating, comment, created_at) VALUES (86, 65, 4, 'Matériaux de bonne qualité.', NOW());
INSERT INTO reviews (product_id, user_id, rating, comment, created_at) VALUES (20, 26, 5, 'Super qualité, je recommande !', NOW());
INSERT INTO reviews (product_id, user_id, rating, comment, created_at) VALUES (99, 72, 5, 'Livraison rapide et produit bien emballé.', NOW());
INSERT INTO reviews (product_id, user_id, rating, comment, created_at) VALUES (7, 83, 3, 'Couleur conforme aux photos.', NOW());
INSERT INTO reviews (product_id, user_id, rating, comment, created_at) VALUES (49, 38, 5, 'Très confortable et stylé.', NOW());
INSERT INTO reviews (product_id, user_id, rating, comment, created_at) VALUES (19, 95, 2, 'Design unique, j''adore.', NOW());
INSERT INTO reviews (product_id, user_id, rating, comment, created_at) VALUES (49, 53, 3, 'Service client réactif.', NOW());
INSERT INTO reviews (product_id, user_id, rating, comment, created_at) VALUES (29, 43, 4, 'Service client réactif.', NOW());
INSERT INTO reviews (product_id, user_id, rating, comment, created_at) VALUES (20, 59, 3, 'Un peu serré, prendre une taille au-dessus.', NOW());
INSERT INTO reviews (product_id, user_id, rating, comment, created_at) VALUES (11, 79, 1, 'Bon rapport qualité/prix.', NOW());
INSERT INTO reviews (product_id, user_id, rating, comment, created_at) VALUES (23, 10, 4, 'Service client réactif.', NOW());
INSERT INTO reviews (product_id, user_id, rating, comment, created_at) VALUES (10, 18, 3, 'Livraison rapide et produit bien emballé.', NOW());
INSERT INTO reviews (product_id, user_id, rating, comment, created_at) VALUES (35, 56, 4, 'Service client réactif.', NOW());
INSERT INTO reviews (product_id, user_id, rating, comment, created_at) VALUES (22, 10, 1, 'Super qualité, je recommande !', NOW());
INSERT INTO reviews (product_id, user_id, rating, comment, created_at) VALUES (19, 55, 5, 'Parfait pour un usage quotidien.', NOW());
INSERT INTO reviews (product_id, user_id, rating, comment, created_at) VALUES (65, 32, 2, 'Couleur conforme aux photos.', NOW());
INSERT INTO reviews (product_id, user_id, rating, comment, created_at) VALUES (31, 78, 1, 'Très confortable et stylé.', NOW());
INSERT INTO reviews (product_id, user_id, rating, comment, created_at) VALUES (84, 41, 2, 'Service client réactif.', NOW());
INSERT INTO reviews (product_id, user_id, rating, comment, created_at) VALUES (25, 23, 2, 'Livraison rapide et produit bien emballé.', NOW());